### PR TITLE
Improve validation error reporting

### PR DESCRIPTION
**Pull request by patrickocoffeyo**
This PR introduces the following adjustments:
 - Allows `semverizedParameters.validator()` to throw an error with multiple validation failure messages.
 - Adjusts `semverizedParameters.validator()` error message so that it includes the path to the problematic property. (This needs improvement, but that'll be a different issue/PR).

## Steps to test
- [ ] Checkout this branch.
- [ ] Run `yarn build`.
- [ ] (probably in a test) pass an object with multiple invalid properties to `semverizedParameters.validator()`.
- [ ] Note that all invalid properties are reported, and note the path to the problematic property is output.

### CODE REVIEW

**Comment by thebruce** [comment]
Great!  Just one error in travis - but perhaps others, for some reason the constructor returned on the toThrow is no longer matching up/

**Comment by patrickocoffeyo** [comment]
Not sure if [this](https://github.com/schemepunk/schema-got-swagger/pull/9/commits/5b6cddcfc0a0e014b74b8c48b7faca96651a1d3f) is the right fix for that test... I wanted to use `expect.arrayContaining()` to expect an array containing `SchemaGotSwaggerError` objects, but that's not how `arrayContaining()` works :roll_eyes:

**Review by thebruce — APPROVED** [review]
Looks great, thanks v much @patrickocoffeyo

**Comment by thebruce** [comment]
Version [1.0.0](https://github.com/schemepunk/schema-got-swagger/releases/tag/1.0.0) has been released.

**Pull request merged**
